<!DOCTYPE html>
<html lang="en">
<head>
  <title>error page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <style>
    body {
      position: relative;
      background-image: url("/img/notFound.jpg");
      background-repeat: no-repeat;
      background-size: 100% 100vh;
    }
  </style>

</head>
<body>
</body>
</html>
